<img src="https://courses.edx.org/asset-v1:ACCA+ML001+2T2021+type@asset+block@acca-logo.jpg" alt="ACCA logo" style="width: 400px;"/>

# Automating Excel using Python
## Part 1 - First steps with xlwings

* **Course:** __Machine learning with Python for finance professionals__ by ACCA
* **Instructor:** [Coefficient](https://coefficient.ai) / [@CoefficientData](https://twitter.com/CoefficientData)

---

In [1]:
import pandas as pd
import xlwings as xw

<div class="alert alert-block alert-info" style="background-color: #BA001E; border: 0px; -moz-border-radius: 10px; -webkit-border-radius: 10px;">
<h2 style="color: white">
xlwings
</h2><br>
</div>

<img src="https://courses.edx.org/asset-v1:ACCA+ML001+2T2021+type@asset+block@xlwings.png" alt="xlwings" style="width: 300px;"/>

[xlwings](https://www.xlwings.org/) is an open source Python library for automating Excel and integrating Excel with the power of Python. Excel worksheets can be controlled from Python, but also Python can be controlled from Excel.

xlwings offers the opportunity to start replacing hard-to-maintain VBA codebases with Python code. Once the VBA functions are re-written in Python, they can be called from within Excel as if they were any other VBA macro.

## Use `xw.view()` to take a quick look at a pandas dataframe
Let's start by reading some data directly from this page on Wikipedia: https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population

In [2]:
df = pd.read_html('https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population')[0]
df

,Rank,Country or dependent territory,Population,% of world,Date,Source (official or United Nations)
0,1,China†[b],1411778724,NaN,1 Nov 2020,2020 census result[3]
1,2,India†[c],1378291227,NaN,17 Jun 2021,National population clock[4]
2,3,United States†[d],331859626,NaN,17 Jun 2021,National population clock[5]
3,4,Indonesia†,271350000,NaN,31 Dec 2020,National annual estimate[6]
4,5,Pakistan†[e],225200000,NaN,1 Jul 2021,UN projection[2]
...,...,...,...,...,...,...
237,–,Tokelau† (NZ),1501,NaN,1 Jul 2021,National annual projection[91]
238,195,Vatican City†[ab],825,NaN,1 Feb 2019,Monthly national estimate[190]
239,–,Cocos (Keeling) Islands† (Australia),573,NaN,30 Jun 2020,National annual estimate[189]
240,–,Pitcairn Islands† (UK),40,NaN,1 Jan 2021,National annual estimate[191]
241,NaN,World,7875418000,100%,17 Jun 2021,UN projection[2]

<div class="alert alert-block alert-danger">
If this doesn't work (e.g. due to corporate firewall blocking pandas from talking to Wikipedia) then you can delete the cell above and uncomment the line below.
</div>

In [3]:
# df = pd.read_csv('population.csv')
# df

<div class="alert alert-block alert-danger">
You may need to open Excel first before running this next cell. If it doesn't work first time, try running the cell again.
</div>

In [4]:
# Let's view this data directly in Excel, using xlwings.
xw.view(df)

In [5]:
# Some of the country names have letters after their names, e.g. "China[b]". These are links 
# to Wikipedia footnotes. We can detect these with the pandas .str.contains() method.

name_contains_footnotes = df['Country or dependent territory'].str.contains("[", regex=False)
df[name_contains_footnotes].head(10)

,Rank,Country or dependent territory,Population,% of world,Date,Source (official or United Nations)
0,1,China†[b],1411778724,NaN,1 Nov 2020,2020 census result[3]
1,2,India†[c],1378291227,NaN,17 Jun 2021,National population clock[4]
2,3,United States†[d],331859626,NaN,17 Jun 2021,National population clock[5]
4,5,Pakistan†[e],225200000,NaN,1 Jul 2021,UN projection[2]
8,9,Russia†[f],146171015,NaN,1 Jan 2021,National annual estimate[9]
19,20,France†[g],67413000,NaN,1 May 2021,Monthly national estimate[18]
20,21,United Kingdom†[h],67113000,NaN,30 Jun 2020,National annual estimate[19]
23,24,Tanzania†[i],59441988,NaN,1 Jul 2021,National annual projection[22]
34,35,Ukraine†[j],41487960,NaN,1 Apr 2021,Monthly national estimate[33]
38,39,Morocco†[k],36281959,NaN,17 Jun 2021,National population clock[37]

In [6]:
# We can handle this using a similar function, the pandas .str.replace() method and
# some nifty regex.

df['Country or dependent territory'] = (df['Country or dependent territory']
                                         .str.replace("\[([a-zA-Z]+)\]", "", regex=True))

In [7]:
df['Country or dependent territory']

0                                    China†
1                                    India†
2                            United States†
3                                Indonesia†
4                                 Pakistan†
                       ...
237                           Tokelau† (NZ)
238                           Vatican City†
239    Cocos (Keeling) Islands† (Australia)
240                  Pitcairn Islands† (UK)
241                                   World
Name: Country or dependent territory, Length: 242, dtype: object

---

<div class="alert alert-block alert-info">
<b>ℹ️ What is regex?</b><br/>

"<em>Regular expressions</em>", or "<em>regex</em>", are a standardised language for matching patterns in strings. They allow us to answer questions like "<a href="https://www.geeksforgeeks.org/find-all-the-numbers-in-a-string-using-regular-expression-in-python/"><b>show me all the numbers in this text document</b></a>", or "<a href="https://pythonexamples.org/python-regex-find-numbers-of-specific-length-in-string/"><b>show me all the numbers of a given length</b></a>" or "<a href="https://stackoverflow.com/questions/16405187/regular-expression-for-uk-mobile-number-python"><b>show me all the UK mobile numbers in this document</b></a>".
<br/><br/>
    
We won't be going into any further detail on regex, but note that pandas supports regex directly (so often you don't need to use Python's `re` module if you're working on a pandas dataframe).
<br/><br/>

If you'd like to try out the regex we used above, go to <a href="https://regex101.com/"><b>https://regex101.com</b></a> and:
<ul>
    <li>Where it says "insert your regular expression here" enter &nbsp; <code>\[[a-zA-Z]+\]</code></li>
    <li>Where it says "insert your test string here" enter &nbsp; <code>China[a] India Pakistan[b] Australia[cd]</code></li>
    <li>Notice how the bits of interest are highlighted in the text. On the right-hand side is displayed an explanation of what each part of the regex string is doing, and the matches found. This is a very useful website if you need to use regex!</li>
</ul>            
    
</div>

---

For now, let's note that we've managed to remove all the footnotes (`[a]`, `[b]`, etc) from country names in our dataframe.

In [8]:
df.head()

,Rank,Country or dependent territory,Population,% of world,Date,Source (official or United Nations)
0,1,China†,1411778724,NaN,1 Nov 2020,2020 census result[3]
1,2,India†,1378291227,NaN,17 Jun 2021,National population clock[4]
2,3,United States†,331859626,NaN,17 Jun 2021,National population clock[5]
3,4,Indonesia†,271350000,NaN,31 Dec 2020,National annual estimate[6]
4,5,Pakistan†,225200000,NaN,1 Jul 2021,UN projection[2]

Time to update the open Excel spreadsheet with our improved country names! The same workbook stays open and can be updated live. We can tell xlwings to update the existing workbook using the second argument, `xw.sheets.active`.

In [9]:
# Note also that the sheets gets cleared with every call.
xw.view(df, xw.sheets.active)

> Close down this workbook when you're ready to move on.

---
<div class="alert alert-block alert-info">
    <b>Please proceed to the next part of the course when you are ready.</b>
</div>